FinSolvers/FinSolvers_Project/FinSolvers_App1/urls.py
from django.conf.urls import url
from FinSolvers_App1 import views

app_name='FinSolvers_App1'

urlpatterns=[
    url(r'^register/$', views.register,name='register'),
    url(r'^user_login/$', views.user_login,name='user_login')
]

FinSolvers/FinSolvers_Project/FinSolvers_Project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from FinSolvers_App1 import views

urlpatterns = [
    url(r'^$', views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^FinSolvers_App1/',include('FinSolvers_App1.urls')),
    url(r'^logout/$',views.user_logout,name='logout')#,
    #url(r'^special/$',views.user_special,name='special')
]

FinSolvers/FinSolvers_Project/FinSolvers_App1/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

FinSolvers/FinSolvers_Project/FinSolvers_App1/forms.py
from django import forms
from django.contrib.auth.models import User
from FinSolvers_App1.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields = ('username','email','password')

FinSolvers/FinSolvers_Project/FinSolvers_App1/views.py
from django.shortcuts import render
from FinSolvers_App1.forms import UserForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def index(request):
    return render(request,'FinSolvers_App1/index.html')

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/FinSolvers_App1/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == "POST":
        user_form=UserForm(data=request.POST)

        if user_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print(user_form.errors)
    else:
        user_form=UserForm()
    return render(request,'FinSolvers_App1/registration.html', {'user_form':user_form,'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'FinSolvers_App1/login.html', {})

FinSolvers/FinSolvers_Project/templates/FinSolvers_App1/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <nav class='navbar navbar-default navbar-static-top'>
            <div class="container">
                <ul class="nav navbar-nav"> 
                    <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
                    <li><a class="nabvbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="nabvbar-link" href="{% url 'FinSolvers_App1:register' %}">Register</a></li>
                    
                    {% if user.is_authenticated %}
                       <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li><a class="navbar-link" href="{% url 'FinSolvers_App1:user_login' %}">Login</a></li>    
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="container">
          {% block body_block %}
          {% endblock %}
        </div>
    </body>
</html>

FinSolvers/FinSolvers_Project/templates/FinSolvers_App1/index.html
{% extends "FinSolvers_App1/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Welcome to FinSolvers HomePage</h1>
</div>

{% endblock %}

FinSolvers/FinSolvers_Project/templates/FinSolvers_App1/login.html
{% extends "FinSolvers_App1/base.html" %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'FinSolvers_App1:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">
        <input type="submit" name="" value="Login">

    </form>
</div>

{% endblock %}

FinSolvers/FinSolvers_Project/templates/FinSolvers_App1/registration.html
{% extends "FinSolvers_App1/base.html" %}
{% load static %}
{% block body_block %}

<div class="container">
<div class="jumbotron">
    <h1>Registration</h1>
    {% if registered %}
        <h1>Thank you for registering!</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>
        {% endif %}
</div>
</div>
{% endblock %}